environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  - '%PYTHON%\\python.exe -m pip install --upgrade setuptools'
  - '%PYTHON%\\python.exe -m pip install pytest hypothesis coverage codecov typing'

test_script:
  - '%PYTHON%\\python.exe -m coverage run --branch setup.py test'
  - '%PYTHON%\\python.exe -m coverage xml -i'
  - '%PYTHON%\\python.exe -m codecov --file coverage.xml'

build: off
